<a href="https://colab.research.google.com/github/Soyane95/GerarSenha/blob/main/python_pessoas_por_cidade.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd

dados = {
    "Nome": ["Ana", "Carlos", "João", "Ana", "Mariana", "Pedro", "Lucas"],
    "Idade": [25, None, 28, 25, None, 23, None],
    "Cidade": ["Rio", "São Paulo", None, "Rio", "Belo Horizonte", "Rio", "Curitiba"]
}

df = pd.DataFrame(dados)
df

      Nome  Idade          Cidade
0      Ana   25.0             Rio
1   Carlos    NaN       São Paulo
2     João   28.0            None
3      Ana   25.0             Rio
4  Mariana    NaN  Belo Horizonte
5    Pedro   23.0             Rio
6    Lucas    NaN        Curitiba

In [3]:
# remover duplicados
df = df.drop_duplicates()

# preencher valores nulos
df["Idade"] = df["Idade"].fillna(0)
df["Cidade"] = df["Cidade"].fillna("Não informado")

df

      Nome  Idade          Cidade
0      Ana   25.0             Rio
1   Carlos    0.0       São Paulo
2     João   28.0   Não informado
4  Mariana    0.0  Belo Horizonte
5    Pedro   23.0             Rio
6    Lucas    0.0        Curitiba

In [4]:
# média de idade
media = df["Idade"].mean()

# quantidade por cidade
cidade = df["Cidade"].value_counts()

print("Média de idade:", media)
print("\nPessoas por cidade:\n", cidade)

Média de idade: 12.666666666666666

Pessoas por cidade:
 Cidade
Rio               2
São Paulo         1
Não informado     1
Belo Horizonte    1
Curitiba          1
Name: count, dtype: int64